name 							"fnitschmann-env"
maintainer 				"Florian Nitschmann"
maintainer_email 	"f.nitschmann@googlemail.com"
license 					"MIT"
description				"Install envoironment for fnitschmann"
version						"1.0"